/**
 * Exports a list of modules provided by SilverStripe
 */
module.exports = () => ({
  'apollo-client': 'ApolloClient',
  'bootstrap-collapse': 'BootstrapCollapse',
  classnames: 'classnames',
  'deep-freeze-strict': 'DeepFreezeStrict',
  'graphql-fragments': 'GraphQLFragments',
  'graphql-tag': 'GraphQLTag',
  history: 'history',
  'isomorphic-fetch': 'IsomorphicFetch',
  i18n: 'i18n',
  jquery: 'jQuery',
  merge: 'merge',
  'page.js': 'Page',
  'react-addons-test-utils': 'ReactAddonsTestUtils',
  'react-dom': 'ReactDom',
  tether: 'Tether',
  'react-apollo': 'ReactApollo',
  'react-bootstrap-ss': 'ReactBootstrap',
  'react-redux': 'ReactRedux',
  'react-router-redux': 'ReactRouterRedux',
  'react-router': 'ReactRouter',
  'react-select': 'ReactSelect',
  'react-addons-css-transition-group': 'ReactAddonsCssTransitionGroup',
  react: 'React',
  'redux-form': 'ReduxForm',
  'redux-thunk': 'ReduxThunk',
  redux: 'Redux',
  config: 'Config',
  qs: 'qs',
  moment: 'moment',
  modernizr: 'modernizr',
  'react-dnd': 'ReactDND',
  'react-dnd-html5-backend': 'ReactDNDHtml5Backend',
  validator: 'validator',

  // provided by silverstripe or modules
  'components/Accordion/Accordion': 'Accordion',
  'components/Accordion/AccordionBlock': 'AccordionBlock',
  'components/Breadcrumb/Breadcrumb': 'Breadcrumb',
  'components/FormAction/FormAction': 'FormAction',
  'components/FormBuilder/FormBuilder': 'FormBuilder',
  'components/FormBuilderModal/FormBuilderModal': 'FormBuilderModal',
  'components/FieldHolder/FieldHolder': 'FieldHolder',
  'components/GridField/GridField': 'GridField',
  'components/Toolbar/Toolbar': 'Toolbar',
  'components/LiteralField/LiteralField': 'LiteralField',
  'components/Preview/Preview': 'Preview',
  'components/ListGroup/ListGroup': 'ListGroup',
  'components/ListGroup/ListGroupItem': 'ListGroupItem',
  'components/FormAlert/FormAlert': 'FormAlert',
  'components/Badge/Badge': 'Badge',
  'containers/FormBuilderLoader/FormBuilderLoader': 'FormBuilderLoader',
  'containers/InsertMediaModal/InsertMediaModal': 'InsertMediaModal',
  'state/breadcrumbs/BreadcrumbsActions': 'BreadcrumbsActions',
  'state/schema/SchemaActions': 'SchemaActions',
  'state/records/RecordsActions': 'RecordsActions',
  'state/records/RecordsActionTypes': 'RecordsActionTypes',
  'lib/DataFormat': 'DataFormat',
  'lib/Backend': 'Backend',
  'lib/ReducerRegister': 'ReducerRegister',
  'lib/ReactRouteRegister': 'ReactRouteRegister',
  'lib/SilverStripeComponent': 'SilverStripeComponent',
  'lib/Router': 'Router',
  'lib/schemaFieldValues': 'schemaFieldValues',
  'lib/Config': 'Config',
  'lib/Injector': 'Injector',
  'lib/reduxFieldReducer': 'reduxFieldReducer',
});
