mappings:
  LeftAndMain: SilverStripe\Admin\LeftAndMain
  ModelAdmin: SilverStripe\Admin\ModelAdmin
  BackLink_Button_ss: SilverStripe\Admin\LeftAndMain
  CMSLoadingScreen_ss: SilverStripe\Admin\LeftAndMain
  LeftAndMain_Menu_ss: SilverStripe\Admin\LeftAndMain
  ModelAdmin_ImportSpec_ss: SilverStripe\Admin\ModelAdmin
  ModelAdmin_Tools_ss: SilverStripe\Admin\ModelAdmin
  SecurityAdmin_MemberImportForm: SilverStripe\Admin\MemberImportForm
  AdminRootController: SilverStripe\Admin\AdminRootController
  CMSBatchAction: SilverStripe\Admin\CMSBatchAction
  CMSBatchActionHandler: SilverStripe\Admin\CMSBatchActionHandler
  CMSMenu: SilverStripe\Admin\CMSMenu
  CMSMenuItem: SilverStripe\Admin\CMSMenuItem
  CMSProfileController: SilverStripe\Admin\CMSProfileController
  GroupImportForm: SilverStripe\Admin\GroupImportForm
  LeftAndMain_HTTPResponse: SilverStripe\Admin\LeftAndMain_HTTPResponse
  LeftAndMain_SearchFilter: SilverStripe\Admin\LeftAndMain_SearchFilter
  LeftAndMainExtension: SilverStripe\Admin\LeftAndMainExtension
  MemberImportForm: SilverStripe\Admin\MemberImportForm
  SecurityAdmin: SilverStripe\Admin\SecurityAdmin
  CMSMenuItemTest: SilverStripe\Admin\Tests\CMSMenuItemTest
  CMSMenuTest: SilverStripe\Admin\Tests\CMSMenuTest
  CMSMenuTest_LeftAndMainController: SilverStripe\Admin\Tests\CMSMenuTest\LeftAndMainController
  CMSMenuTest_CustomTitle: SilverStripe\Admin\Tests\CMSMenuTest\CustomTitle
  CMSProfileControllerTest: SilverStripe\Admin\Tests\CMSProfileControllerTest
  CMSProfileControllerTestExtension: SilverStripe\Admin\Tests\CMSProfileControllerTest\TestExtension
  LeftAndMainTest: SilverStripe\Admin\Tests\LeftAndMainTest
  ModelAdminTest: SilverStripe\Admin\Tests\ModelAdminTest
  ModelAdminTest_Admin: SilverStripe\Admin\Tests\ModelAdminTest\ContactAdmin
  ModelAdminTest_PlayerAdmin: SilverStripe\Admin\Tests\ModelAdminTest\PlayerAdmin
  ModelAdminTest_Contact: SilverStripe\Admin\Tests\ModelAdminTest\Contact
  ModelAdminTest_Player: SilverStripe\Admin\Tests\ModelAdminTest\Player
  SecurityAdminTest: SilverStripe\Admin\Tests\SecurityAdminTest
