// This file was generated by silverstripe/tx-translator from client/lang/src/en.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "Admin.ANY": "Any",
    "Admin.ARCHIVECONFIRMMESSAGE": "Are you sure you want to archive this record?",
    "Admin.ARCHIVE_CONFIRM_MESSAGE": "Archived",
    "Admin.BATCH_ARCHIVE_PROMPT": "You have {num} page(s) selected.\n\nAre you sure you want to archive these pages?\n\nThese pages and all of their children pages will be unpublished and sent to the archive.",
    "Admin.BATCH_DELETELIVE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete these pages from live?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nAre you sure you want to delete these pages?\n\nThese pages and all of their children pages will be deleted and sent to the archive.",
    "Admin.BATCH_PUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to publish?",
    "Admin.BATCH_RESTORE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to restore to stage?\n\nChildren of archived pages will be restored to the root level, unless those pages are also being restored.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to unpublish",
    "Admin.CLOSE": "Close",
    "Admin.COLLAPSEPANEL": "Collapse panel",
    "Admin.CONFIRMUNSAVED": "Are you sure you want to navigate away from this page?\n\nWARNING: Your changes have not been saved.\n\nPress OK to continue, or Cancel to stay on the current page.",
    "Admin.CONFIRMUNSAVEDSHORT": "WARNING: Your changes have not been saved.",
    "Admin.DELETECONFIRMMESSAGE": "Are you sure you want to delete this record?",
    "Admin.DELETE_CONFIRM_MESSAGE": "Deleted",
    "Admin.EDIT": "Edit",
    "Admin.EDIT_LINK": "Edit link",
    "Admin.ENTER_PASSWORD": "Enter your password",
    "Admin.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later.",
    "Admin.EXPANDPANEL": "Expand panel",
    "Admin.FormatExample": "Example: {format}",
    "Admin.NONE": "None",
    "Admin.NO_OPTIONS": "No options",
    "Admin.NO_SIZE": "N/A",
    "Admin.REMOVE_LINK": "Remove link",
    "Admin.SELECTONEPAGE": "Please select at least one page",
    "Admin.TYPE_TO_SEARCH": "Type to search",
    "Admin.VALIDATIONERROR": "Validation Error",
    "Admin.VALIDATION_ERRORS_IN_TAB": "This tab contains validation errors.",
    "Admin.VALIDATION_ERRORS_IN_TAB_SCREEN_READER": "(Has validation errors)",
    "Admin.VALIDATION_ERRORS_ON_PAGE": "There are validation errors on this page, please fix them before saving or publishing.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} is not only letters.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} is not an alphanumeric value.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} is not a proper date format.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} is not a valid value.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} are not equal.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} is not a number.",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} is required.",
    "Admin.VERIFY": "Verify",
    "Admin.VERIFY_ITS_YOU": "Verify it's you first.",
    "Admin.VERIFY_TO_CONTINUE": "Verify to continue",
    "Admin.WHATS_THIS": "What is this?"
});
}