// This file was generated by silverstripe/tx-translator from client/lang/src/fa_IR.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fa_IR', {
    "Admin.BATCH_ARCHIVE_PROMPT": "شما {num} صفحه(صفحه‌ها) را انتخاب کرده‌اید.\n\n\nآیا از این‌که می‌خواهید بایگانی شوند اطمینان دارید؟\n\nتمامی این صفحات و تمامی صفحات فرزند آن‌ها عدم انتشار می‌شوند و به بایگانی ارسال می‌گردند.",
    "Admin.BATCH_DELETELIVE_PROMPT": "شما {num} صفحه(صفحه‌ها) را انتخاب کرده‌اید.\n\nآیا واقعاً می‌خواهید آن‌ها از لایو را حذف نمایید؟",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "شما {num} صفحه(صفحه‌ها) را انتخاب کرده‌اید.\n\nآیا واقعاً می‌خواهید آن‌ها را منتشر نمایید؟",
    "Admin.BATCH_UNPUBLISH_PROMPT": "شما {num} صفحه را انتخاب کرده‌اید.\n\nآیا واقعاً می‌خواهید انتشار آن‌ها را لغو نمایید",
    "Admin.CONFIRMUNSAVEDSHORT": "هشدار: تغییرات شما ذخیره نشده‌اند.",
    "Admin.SELECTONEPAGE": "لطفاً حداقل ۱ صفحه را انتخاب نمایید.",
    "Admin.VALIDATIONERROR": "خطای اعتبار‌سنجی"
});
}