// This file was generated by silverstripe/tx-translator from client/lang/src/fr.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fr', {
    "Admin.ANY": "Tout",
    "Admin.ARCHIVECONFIRMMESSAGE": "Êtes-vous sûr de vouloir archiver cet enregistrement?",
    "Admin.BATCH_ARCHIVE_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir archiver ces pages?\n\nCes pages et toutes leurs page descendantes seront dépubliées et archivées.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir dépublier ces pages?",
    "Admin.BATCH_DELETE_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir supprimer ces pages?",
    "Admin.BATCH_PUBLISH_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir publier ces pages?",
    "Admin.BATCH_RESTORE_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir les restaurer au site brouillon?\n\nLes pages dépendantes d'une page archivée seront restaurées à la racine du site, sauf si la page parente a également été restaurée.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir les dépublier?",
    "Admin.CLOSE": "Fermer",
    "Admin.COLLAPSEPANEL": "Fermer le panneau",
    "Admin.CONFIRMUNSAVED": "Êtes-vous sûr de vouloir quitter cette page ?\n\nATTENTION: Vos changements n'ont pas été sauvegardés.\n\nCliquez sur OK pour continuer, ou sur Annuler pour rester sur la page actuelle.",
    "Admin.CONFIRMUNSAVEDSHORT": "ATTENTION: Vos changements n'ont pas été sauvegardés.",
    "Admin.DELETECONFIRMMESSAGE": "Êtes-vous sûr de vouloir supprimer cet enregistrement?",
    "Admin.EDIT": "Éditer",
    "Admin.EDIT_MODE": "Mode édition",
    "Admin.EXPANDPANEL": "Ouvrir le panneau",
    "Admin.FormatExample": "Exemple: {format}",
    "Admin.INSERT_LINK": "Ajouter un lien",
    "Admin.NONE": "Aucun",
    "Admin.PREVIEW_MODE": "Mode prévisualisation",
    "Admin.SELECTONEPAGE": "Sélectionner au moins un page",
    "Admin.SPLIT_MODE": "Mode divisé",
    "Admin.VALIDATIONERROR": "Erreur de validation",
    "Admin.VALIDATION_ERRORS_IN_TAB_SCREEN_READER": "(contient des erreurs de validation)",
    "Admin.VALIDATION_ERRORS_ON_PAGE": "Cette page contient des erreurs de validation. Merci de les solutionner avant de sauvegarder ou de publier.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} n'est pas composé uniquement de lettres.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} n'est pas une valeur alpha-numérique.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} n'est pas un format de date valide.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} n'est pas une valeur valide.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} ne sont pas identiques.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} n'est pas un nombre.",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} est requis.",
    "Boolean.ANY": "Tout"
});
}