// This file was generated by silverstripe/cow from client/lang/src/fr.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fr', {
    "Admin.BATCH_ARCHIVE_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir archiver ces pages?\n\nCes pages et toutes leurs page descendantes seront dépubliées et archivées.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir dépublier ces pages?",
    "Admin.BATCH_DELETE_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir supprimer ces pages?",
    "Admin.BATCH_PUBLISH_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir publier ces pages?",
    "Admin.BATCH_RESTORE_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir les restaurer au site brouillon?\n\nLes pages dépendantes d'une page archivée seront restaurées à la racine du site, sauf si la page parente a également été restaurée.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Vous avez sélectionné {num} page(s).\n\nÊtes-vous sûr de vouloir les dépublier?",
    "Admin.SELECTONEPAGE": "Sélectionner au moins un page.",
    "Admin.FormatExample": "Exemple: {format}",
    "Admin.NO_SIZE": "N/A",
    "Admin.CLOSE": "Fermer",
    "Admin.CONFIRMUNSAVED": "Etes-vous sûr de vouloir quitter cette page ?\n\nATTENTION: Vos changements n'ont pas été sauvegardés.\n\nCliquez sur OK pour continuer, ou sur Annuler pour rester sur la page actuelle.",
    "Admin.CONFIRMUNSAVEDSHORT": "ATTENTION: Vos changements n'ont pas été sauvegardés.",
    "Admin.VALIDATIONERROR": "Erreur de validation",
    "Admin.NONE": "Aucun",
    "Admin.EDIT": "Éditer",
    "Admin.ANY": "Tout",
    "Admin.ERRORINTRANSACTION": "Une erreur est survenue lors du transfert de donnée à partir du serveur.\nSVP réessayez plus tard.",
    "Admin.DELETECONFIRMMESSAGE": "Etes-vous sûr de vouloir supprimer cet enregistrement?",
    "Admin.ARCHIVECONFIRMMESSAGE": "Are you sure you want to archive this record?",
    "Admin.EXPANDPANEL": "Ouvrir le panneau",
    "Admin.COLLAPSEPANEL": "Fermer le panneau",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} est requis.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} ne sont pas identiques.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} n'est pas un nombre.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} n'est pas un format de date valide.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} n'est pas une valeur alpha-numérique.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} n'est pas composé uniquement de lettres.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} n'est pas une valeur valide."
});
}