// This file was generated by silverstripe/cow from client/lang/src/hr.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('hr', {
    "Admin.BATCH_ARCHIVE_PROMPT": "Imate {num} stranicu(e) označeno.\n\nJeste li sigurni da želite arhivirati ove stranice?\n\nOve stranice i sve stranice ispod nje će biti neobjavljene i poslane u arhivu.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Imate {num} stranica(e) označeno.\n\nJeste li sigurni da želite obrisati ove stranice s objavljenog?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "Označili ste {num} stranicu(a).\n\nJeste li sigurni da želite objaviti?",
    "Admin.BATCH_RESTORE_PROMPT": "Imate {num} stranica(e) označeno.\n\nJeste li sigurni da želite vratiti ove stranice?\n\nSve podstranice će biti vraćene u najviši nivo, osim ako te stranice su vraćene.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Označili ste {num} stranicu(a).\n\nJeste li sigurni da želite odjaviti?",
    "Admin.SELECTONEPAGE": "Molimo odaberite bar jednu stranicu",
    "Admin.FormatExample": "Example: {format}",
    "Admin.NO_SIZE": "N/A",
    "Admin.CLOSE": "Close",
    "Admin.CONFIRMUNSAVED": "Jeste li sigurni da želite otići s ove stranice?\n\nUPOZORENJE: Vaše promjene nisu spremljene.\n\nPritisnike OK za nastavka, ili Odustani za ostati na trenutnoj stranici.",
    "Admin.CONFIRMUNSAVEDSHORT": "UPOZORENJE: Vaše promjene nisu spremljene.",
    "Admin.VALIDATIONERROR": "Greška validacije",
    "Admin.NONE": "None",
    "Admin.EDIT": "Edit",
    "Admin.ANY": "Any",
    "Admin.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later.",
    "Admin.DELETECONFIRMMESSAGE": "Are you sure you want to delete this record?",
    "Admin.EXPANDPANEL": "Expand panel",
    "Admin.COLLAPSEPANEL": "Collapse panel",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} is required.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} are not equal.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} is not a number.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} is not a proper date format.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} is not an alphanumeric value.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} is not only letters.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} is not a valid value."
});
}