// This file was generated by silverstripe/tx-translator from client/lang/src/it.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('it', {
    "Admin.ARCHIVECONFIRMMESSAGE": "Sicuro di voler archiviare questo record?",
    "Admin.BATCH_ARCHIVE_PROMPT": "Hai selezionato {num} pagina(e).\n\nSei sicuro di volerle archiviare?\n\nQueste pagine insieme a tutte le pagine figlio saranno spubblicate ed archiviate.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Hai {num} pagine selezionate.\n\nVuoi veramente eliminare queste pagine dal sito live?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "Hai {num} pagine selezionate.\n\nVuoi veramente pubblicarle?",
    "Admin.BATCH_RESTORE_PROMPT": "Hai selezionato {num} pagina(e).\n\nSei sicuri di volerle ripristinare?\n\nI figli delle pagine archiviate saranno ripristinati nel primo livello, a meno anche i genitori non vengano ripristinati.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Hai {num} pagine selezionate.\n\nVuoi veramente nasconderle?",
    "Admin.CONFIRMUNSAVED": "Siete sicuri di voler uscire da questa pagina?\n\nATTENZIONE: I vostri cambiamenti non sono stati salvati.\n\nCliccare OK per continuare, o su Annulla per rimanere sulla pagina corrente.",
    "Admin.CONFIRMUNSAVEDSHORT": "ATTENZIONE: le tue modifiche non sono state salvate.",
    "Admin.EDIT_MODE": "Modalità modifica",
    "Admin.INSERT_LINK": "Inserisci il link",
    "Admin.PREVIEW_MODE": "Modalità anteprima",
    "Admin.SELECTONEPAGE": "Per favore selezionare almeno una pagina",
    "Admin.SPLIT_MODE": "Modalità divisa",
    "Admin.VALIDATIONERROR": "Errore di validazione",
    "Admin.VALIDATION_ERRORS_IN_TAB": "Sono presenti errori di validazione in questa scheda.",
    "Admin.VALIDATION_ERRORS_IN_TAB_SCREEN_READER": "(errori di validazione)",
    "Admin.VALIDATION_ERRORS_ON_PAGE": "Sono presenti errori di validazione in questa pagina: correggerli prima di salvare o pubblicare.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} non sono solo lettere.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} non è un valore alfanumerico.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} non è un formato data corretto.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} non è un valore valido.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} non sono uguali.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} non è un numero.",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} è obbligatorio."
});
}