// This file was generated by silverstripe/tx-translator from client/lang/src/ja.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ja', {
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.CONFIRMUNSAVED": "このページから移動しても良いですか?\n\n警告: あなたの変更は保存されていません．\n\n続行するにはOKを押してください．キャンセルをクリックするとこのページにとどまります．",
    "Admin.CONFIRMUNSAVEDSHORT": "警告: あなたの変更は保存されていません．",
    "Admin.VALIDATIONERROR": "検証エラー"
});
}