// This file was generated by silverstripe/tx-translator from client/lang/src/lt.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('lt', {
    "Admin.BATCH_ARCHIVE_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite archyvuoti šiuos puslapius?\n\nŠie puslapiai ir visi po jais esantys puslapiai bus nebepublikuojami ir suarchyvuoti.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite ištrinti iš publikuotų puslapių?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite publikuoti?",
    "Admin.BATCH_RESTORE_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite atstatyti?\n\nPuslapiai, esantys po suarchyvuotais puslapiais, bus atstatyti aukščiausiame lygyje, nebent šie puslapiai irgi bus atstatyti.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite nebepublikuoti?",
    "Admin.CONFIRMUNSAVED": "Ar tikrai norite išeiti iš šio puslapio?\n\nDĖMESIO: Jūsų pakeitimai neišsaugoti.\n\nNorėdami tęsti, spauskite OK, jeigu norite likti, spauskite Cancel.",
    "Admin.CONFIRMUNSAVEDSHORT": "DĖMESIO: Jūsų pakeitimai neišsaugoti.",
    "Admin.SELECTONEPAGE": "Prašome pasirinkti bent vieną puslapį",
    "Admin.VALIDATIONERROR": "Tikrinimo klaida"
});
}