// This file was generated by silverstripe/cow from client/lang/src/lt.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('lt', {
    "Admin.BATCH_ARCHIVE_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite archyvuoti šiuos puslapius?\n\nŠie puslapiai ir visi po jais esantys puslapiai bus nebepublikuojami ir suarchyvuoti.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite ištrinti iš publikuotų puslapių?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite publikuoti?",
    "Admin.BATCH_RESTORE_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite atstatyti?\n\nPuslapiai, esantys po suarchyvuotais puslapiais, bus atstatyti aukščiausiame lygyje, nebent šie puslapiai irgi bus atstatyti.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Pažymėjote {num} puslapius(-į).\n\nAr tikrai norite nebepublikuoti?",
    "Admin.SELECTONEPAGE": "Prašome pasirinkti bent vieną puslapį",
    "Admin.FormatExample": "Example: {format}",
    "Admin.NO_SIZE": "N/A",
    "Admin.CLOSE": "Close",
    "Admin.CONFIRMUNSAVED": "Ar tikrai norite išeiti iš šio puslapio?\n\nDĖMESIO: Jūsų pakeitimai neišsaugoti.\n\nNorėdami tęsti, spauskite OK, jeigu norite likti, spauskite Cancel.",
    "Admin.CONFIRMUNSAVEDSHORT": "DĖMESIO: Jūsų pakeitimai neišsaugoti.",
    "Admin.VALIDATIONERROR": "Tikrinimo klaida",
    "Admin.NONE": "None",
    "Admin.EDIT": "Edit",
    "Admin.ANY": "Any",
    "Admin.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later.",
    "Admin.DELETECONFIRMMESSAGE": "Are you sure you want to delete this record?",
    "Admin.EXPANDPANEL": "Expand panel",
    "Admin.COLLAPSEPANEL": "Collapse panel",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} is required.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} are not equal.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} is not a number.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} is not a proper date format.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} is not an alphanumeric value.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} is not only letters.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} is not a valid value."
});
}