// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "Admin.BATCH_ARCHIVE_PROMPT": "Je hebt {num} pagina(s) geselecteerd.\n\nWeet je zeker dat je de pagina(s) wilt archiveren?\n\nDe publicatie van deze en onderliggende pagina's wordt ingetrokken en gearchiveerd.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Je hebt {num} pagina(s) geselecteerd.\n\nWeet je zeker dat je de publicatie van deze pagina's wilt intrekken?",
    "Admin.BATCH_DELETE_PROMPT": "Je hebt {num} pagina(s) geselecteerd.\n\nWeet je zeker dat je deze wilt verwijderen?",
    "Admin.BATCH_PUBLISH_PROMPT": "Je hebt {num} pagina(s) geselecteerd.\n\nWeet je zeker dat je de pagina(s) wilt publiceren?",
    "Admin.BATCH_RESTORE_PROMPT": "Je hebt {num} pagina(s) geselecteerd.\n\nWeet je zeker dat je de pagina(s) wilt herstellen? Onderliggende pagina's worden naar het top level hersteld, tenzij deze pagina's ook worden hersteld.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Je hebt {num} pagina(s) geselecteerd.\n\nWeet je zeker dat je de publicatie wilt intrekken?",
    "Admin.SELECTONEPAGE": "Selecteer minstens 1 pagina.",
    "Admin.FormatExample": "Voorbeeld: {format}",
    "Admin.NO_SIZE": "N/A",
    "Admin.CLOSE": "Sluiten",
    "Admin.CONFIRMUNSAVED": "Weet u zeker dat u deze pagina wilt verlaten?\nWAARSCHUWING: Uw veranderingen zijn niet opgeslagen.\n\nKies OK om te verlaten, of Cancel om op de huidige pagina te blijven.",
    "Admin.CONFIRMUNSAVEDSHORT": "WAARSCHUWING: Uw veranderingen zijn niet opgeslagen",
    "Admin.VALIDATIONERROR": "Validatiefout",
    "Admin.NONE": "Geen",
    "Admin.EDIT": "Edit",
    "Admin.ANY": "Any",
    "Admin.ERRORINTRANSACTION": "Er is een fout opgetreden bij het ophalen van gegevens van de server\nProbeer het later nog eens.",
    "Admin.DELETECONFIRMMESSAGE": "Are you sure you want to delete this record?",
    "Admin.ARCHIVECONFIRMMESSAGE": "Are you sure you want to archive this record?",
    "Admin.EXPANDPANEL": "Expand panel",
    "Admin.COLLAPSEPANEL": "Collapse panel",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} is vereist.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} komen niet overeen.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} is niet numeriek.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} is niet in het juiste datum formaat.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} is geen alpha numerieke waarde.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} bestaat niet alleen uit letters.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} is geen geldige waarde."
});
}