// This file was generated by silverstripe/cow from client/lang/src/pl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "Admin.BATCH_ARCHIVE_PROMPT": "Wybrałeś {num} strona(y)\n\nCzy na pewno chcesz zarchiwizować te strony? \n\nTe strony i wszystkie ich strony podrzędne będą niepublikowane i wysłane do archiwum.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Wybrałeś {num} strona(y)\n\nCzy na pewno chcesz cofnąć publikację?",
    "Admin.BATCH_DELETE_PROMPT": "Wybrałeś {num} strona(y)\n\nCzy na pewno chcesz usunąć te strony? \n\nTe strony i wszystkie ich strony podrzędne zostaną usunięte i wysłane do archiwum.",
    "Admin.BATCH_PUBLISH_PROMPT": "Wybrałeś {num} strona(y)\n\nCzy na pewno chcesz dokonać publikacji?",
    "Admin.BATCH_RESTORE_PROMPT": "Wybrałeś {num} strona(y)\n\nCzy na pewno chcesz je przywrócić? \n\nDzieci z zarchiwizowanych stron zostaną przywrócone do poziomu głównego, chyba że te strony również zostaną przywrócone.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Wybrano {num} stron(y).\n\nCzy na pewno chcesz cofnąć publikację?",
    "Admin.SELECTONEPAGE": "Wybierz co najmniej jedną stronę",
    "Admin.FormatExample": "Przykład: {format}",
    "Admin.NO_SIZE": "Nie dotyczy",
    "Admin.CLOSE": "Zamknij",
    "Admin.CONFIRMUNSAVED": "Czy na pewno chcesz kontynuować nawigację poza tą stronę?\n\nUWAGA: Twoje zmiany nie zostały zapisane.\n\nWciśnij OK aby kontynuować, wciśnij Anuluj aby pozostać na tej stronie.",
    "Admin.CONFIRMUNSAVEDSHORT": "UWAGA: Twoje zmiany nie zostały zapisane.",
    "Admin.VALIDATIONERROR": "Niepoprawne dane",
    "Admin.NONE": "Żaden",
    "Admin.EDIT": "Edytuj",
    "Admin.ANY": "Każdy",
    "Admin.ERRORINTRANSACTION": "Wystąpił błąd podczas pobierania danych z serwera\nSpróbuj ponownie później.",
    "Admin.DELETECONFIRMMESSAGE": "Czy na pewno chcesz usunąć ten rekord?",
    "Admin.EXPANDPANEL": "Rozwiń panel",
    "Admin.COLLAPSEPANEL": "Zwiń panel",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} jest wymagane.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} nie są takie same.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} nie jest liczbą.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} nie jest prawidłowym formatem daty,",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} nie jest wartością alfanumeryczną.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "Pole {name} wymaga jedynie liter.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} nie jest prawidłową wartością."
});
}