// This file was generated by silverstripe/cow from client/lang/src/pl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "Admin.BATCH_ARCHIVE_PROMPT": "You have {num} page(s) selected.\n\nAre you sure you want to archive these pages?\n\nThese pages and all of their children pages will be unpublished and sent to the archive.",
    "Admin.BATCH_DELETELIVE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete these pages from live?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to publish?",
    "Admin.BATCH_RESTORE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to restore to stage?\n\nChildren of archived pages will be restored to the root level, unless those pages are also being restored.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to unpublish",
    "Admin.SELECTONEPAGE": "Please select at least one page",
    "Admin.FormatExample": "Example: {format}",
    "Admin.NO_SIZE": "N/A",
    "Admin.CLOSE": "Close",
    "Admin.CONFIRMUNSAVED": "Czy na pewno chcesz kontynuować nawigację poza tą stronę?\n\nUWAGA: Twoje zmiany nie zostały zapisane.\n\nWciśnij OK aby kontynuować, wciśnij Anuluj aby pozostać na tej stronie.",
    "Admin.CONFIRMUNSAVEDSHORT": "UWAGA: Twoje zmiany nie zostały zapisane.",
    "Admin.VALIDATIONERROR": "Niepoprawne dane",
    "Admin.NONE": "None",
    "Admin.EDIT": "Edit",
    "Admin.ANY": "Any",
    "Admin.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later.",
    "Admin.DELETECONFIRMMESSAGE": "Are you sure you want to delete this record?",
    "Admin.EXPANDPANEL": "Expand panel",
    "Admin.COLLAPSEPANEL": "Collapse panel"
});
}