// This file was generated by silverstripe/tx-translator from client/lang/src/sk.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "Admin.ANY": "Any",
    "Admin.ARCHIVECONFIRMMESSAGE": "Are you sure you want to archive this record?",
    "Admin.BATCH_ARCHIVE_PROMPT": "Vybrali ste {num} stránok.\n\nUrčite chcete archivovať tieto stránky?\n\nTieto stránky a jej všetky podstránky budú nezverejnené a odoslané do archívu.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Máte vybratých {num} stránok.\n\nSkutočne chcete tieto stránky vymazať z webu?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "Máte vybratých {num} stránok.\n\nSkutočne ich chcete zverejniť?",
    "Admin.BATCH_RESTORE_PROMPT": "Vybrali ste {num} stránok.\n\nSkutočne chcete obnoviť?\n\nPodstránky archivovaných stránok budú obnovené do najvyššej úrovne, pokiaľ tieto stránky budú tiež obnovené.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Máte vybratých {num} stránok.\n\nSkutočne ich chcete nezverejniť?",
    "Admin.CLOSE": "Close",
    "Admin.COLLAPSEPANEL": "Collapse panel",
    "Admin.CONFIRMUNSAVED": "Určite chcete opustiť navigáciu z tejto stránky?\n\nUPOZORNENIE: Vaše zmeny neboli uložené.\n\nStlačte OK pre pokračovať, alebo Cancel, ostanete na teto stránke.",
    "Admin.CONFIRMUNSAVEDSHORT": "UPOZORNENIE: Vaše zmeny neboli uložené.",
    "Admin.DELETECONFIRMMESSAGE": "Are you sure you want to delete this record?",
    "Admin.EDIT": "Edit",
    "Admin.EDIT_LINK": "Edit link",
    "Admin.ENTER_PASSWORD": "Enter your password",
    "Admin.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later.",
    "Admin.EXPANDPANEL": "Expand panel",
    "Admin.FormatExample": "Example: {format}",
    "Admin.NONE": "None",
    "Admin.NO_SIZE": "N/A",
    "Admin.REMOVE_LINK": "Remove link",
    "Admin.SELECTONEPAGE": "Prosím, vyberte najmenej 1 stránku",
    "Admin.VALIDATIONERROR": "Chyba platnosti",
    "Admin.VALIDATION_ERRORS_IN_TAB": "This tab contains validation errors.",
    "Admin.VALIDATION_ERRORS_IN_TAB_SCREEN_READER": "(Has validation errors)",
    "Admin.VALIDATION_ERRORS_ON_PAGE": "There are validation errors on this page, please fix them before saving or publishing.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} is not only letters.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} is not an alphanumeric value.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} is not a proper date format.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} is not a valid value.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} are not equal.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} is not a number.",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} is required.",
    "Admin.VERIFY": "Verify",
    "Admin.VERIFY_ITS_YOU": "Verify it's you first.",
    "Admin.VERIFY_TO_CONTINUE": "Verify to continue",
    "Admin.WHATS_THIS": "What is this?"
});
}