// This file was generated by silverstripe/tx-translator from client/lang/src/sl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "Admin.ANY": "Poljuben",
    "Admin.ARCHIVECONFIRMMESSAGE": "Ali res želite arhivirati ta zapis?",
    "Admin.ARCHIVE_CONFIRM_MESSAGE": "Archived",
    "Admin.BATCH_ARCHIVE_PROMPT": "You have {num} page(s) selected.\n\nAre you sure you want to archive these pages?\n\nThese pages and all of their children pages will be unpublished and sent to the archive.",
    "Admin.BATCH_DELETELIVE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete these pages from live?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to publish?",
    "Admin.BATCH_RESTORE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to restore to stage?\n\nChildren of archived pages will be restored to the root level, unless those pages are also being restored.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to unpublish",
    "Admin.CLOSE": "Zapri",
    "Admin.COLLAPSEPANEL": "Zloži deščico",
    "Admin.CONFIRMUNSAVED": "Res želite zapusitit stran?\n\nOPOZORILO: spremembe niso bile shranjene\n\nKliknite OK za nadaljevanje ali Prekliči, da ostanete na trenutni strani.",
    "Admin.CONFIRMUNSAVEDSHORT": "OPOZORILO: spremembe niso bile shranjene.",
    "Admin.DELETECONFIRMMESSAGE": "Ste prepričani, da želite izbrisati ta vnos?",
    "Admin.DELETE_CONFIRM_MESSAGE": "Deleted",
    "Admin.EDIT": "Uredi",
    "Admin.EDIT_LINK": "Edit link",
    "Admin.ENTER_PASSWORD": "Vnesite vaše geslo",
    "Admin.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later.",
    "Admin.EXPANDPANEL": "Razpri deščico",
    "Admin.FormatExample": "Primer: {format}",
    "Admin.NONE": "Brez",
    "Admin.NO_OPTIONS": "No options",
    "Admin.NO_SIZE": "ni podatka",
    "Admin.REMOVE_LINK": "Remove link",
    "Admin.SELECTONEPAGE": "Izberite vsaj eno možnost",
    "Admin.TYPE_TO_SEARCH": "Type to search",
    "Admin.VALIDATIONERROR": "Napaka pri preverjanju",
    "Admin.VALIDATION_ERRORS_IN_TAB": "V zavihku so napačni podatki.",
    "Admin.VALIDATION_ERRORS_IN_TAB_SCREEN_READER": "(Vsebuje napačne podatke)",
    "Admin.VALIDATION_ERRORS_ON_PAGE": "Na strani so napačni podatki. Popravite jih, preden boste stran shranili ali objavili.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} niso samo črke.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} ni alfanumerična vrednost.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} ni pravilna oblika datuma.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} ni veljavna vrednost.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} se ne ujema.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} ni število.",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} morate izpolniti.",
    "Admin.VERIFY": "Preveri",
    "Admin.VERIFY_ITS_YOU": "Najprej potrdite, da ste to res vi.",
    "Admin.VERIFY_TO_CONTINUE": "Za nadaljevanje potrdite",
    "Admin.WHATS_THIS": "Kaj je to?"
});
}