// This file was generated by silverstripe/cow from client/lang/src/sl_SI.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl_SI', {
    "Admin.BATCH_ARCHIVE_PROMPT": "Izbrano število strani: {num}\n\nSte prepričani, da želite arhivirati te strani?\n\nTe strani in vse ostale podstrani bodo odstranjene iz objave in premaknjene v arhiv.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Izbrali ste {num} strani.\n\nAli ste prepričani, da želite izbrisati te strani iz objave?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to publish?",
    "Admin.BATCH_RESTORE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to restore to stage?\n\nChildren of archived pages will be restored to the root level, unless those pages are also being restored.",
    "Admin.BATCH_UNPUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to unpublish",
    "Admin.SELECTONEPAGE": "Prosimo izberite vsaj eno stran",
    "Admin.FormatExample": "Example: {format}",
    "Admin.NO_SIZE": "N/A",
    "Admin.CLOSE": "Close",
    "Admin.CONFIRMUNSAVED": "Are you sure you want to navigate away from this page?\n\nWARNING: Your changes have not been saved.\n\nPress OK to continue, or Cancel to stay on the current page.",
    "Admin.CONFIRMUNSAVEDSHORT": "POZOR: Spremembe niso bile shranjene.",
    "Admin.VALIDATIONERROR": "Napaka pri validaciji",
    "Admin.NONE": "None",
    "Admin.EDIT": "Edit",
    "Admin.ANY": "Any",
    "Admin.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later.",
    "Admin.DELETECONFIRMMESSAGE": "Are you sure you want to delete this record?",
    "Admin.EXPANDPANEL": "Expand panel",
    "Admin.COLLAPSEPANEL": "Collapse panel",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} is required.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} are not equal.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} is not a number.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} is not a proper date format.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} is not an alphanumeric value.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} is not only letters.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} is not a valid value."
});
}