// This file was generated by silverstripe/tx-translator from client/lang/src/sr@latin.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sr@latin', {
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.CONFIRMUNSAVED": "Da li ste sigurni da želite da odete sa ove stranice?\n\nUPOZORENjE: Vaše izmene još nisu sačuvane.\n\nPritisnite U redu za nastavak ili Odustani da bi ste ostali na ovoj stranici.",
    "Admin.CONFIRMUNSAVEDSHORT": "UPOZORENjE: Vaše izmene nisu sačuvane.",
    "Admin.VALIDATIONERROR": "Grešla pri proveri ispravnosti"
});
}