// This file was generated by silverstripe/cow from client/lang/src/sv.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "Admin.BATCH_ARCHIVE_PROMPT": "Du har {num} sida/sidor valda.\n\n\nÄr du säker på att du vill arkivera dessa sidor?\n\n\nDessa sidor och sidornas undersidor kommer att avpubliceras och arkiveras.",
    "Admin.BATCH_DELETELIVE_PROMPT": "Du har valt {num} sida/sidor\n\nVill du verkligen radera dem från den publicerade sidan?",
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "Du har valt {num} sida/sidor.\nVill du verkligen publicera dem.",
    "Admin.BATCH_RESTORE_PROMPT": "Du har {num} sida/sidor valda. \n\nVill du verkligen återställa till ett tidigare skede?\n\nUndersidor till arkiverade sidor kommer att återställas till rotnivå , såvida dessa sidor också återställs .",
    "Admin.BATCH_UNPUBLISH_PROMPT": "Du har valt {num} sida/sidor\n\nVill du verkligen avpublicera",
    "Admin.SELECTONEPAGE": "Var vänlig och välj minst en sida",
    "Admin.FormatExample": "Example: {format}",
    "Admin.NO_SIZE": "N/A",
    "Admin.CLOSE": "Close",
    "Admin.CONFIRMUNSAVED": "Är du säker på att du vill lämna denna sida?\n\nVARNING: Dina ändringar har inte sparats.\n\nTryck OK för att lämna sidan eller Avbryt för att stanna på aktuell sida.",
    "Admin.CONFIRMUNSAVEDSHORT": "WARNING: Your changes have not been saved.",
    "Admin.VALIDATIONERROR": "Valideringsfel",
    "Admin.NONE": "None",
    "Admin.EDIT": "Edit",
    "Admin.ANY": "Any",
    "Admin.ERRORINTRANSACTION": "An error occured while fetching data from the server\n Please try again later.",
    "Admin.DELETECONFIRMMESSAGE": "Are you sure you want to delete this record?",
    "Admin.EXPANDPANEL": "Expand panel",
    "Admin.COLLAPSEPANEL": "Collapse panel",
    "Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} is required.",
    "Admin.VALIDATOR_MESSAGE_EQUALS": "{name} are not equal.",
    "Admin.VALIDATOR_MESSAGE_NUMERIC": "{name} is not a number.",
    "Admin.VALIDATOR_MESSAGE_DATE": "{name} is not a proper date format.",
    "Admin.VALIDATOR_MESSAGE_ALPHANUMERIC": "{name} is not an alphanumeric value.",
    "Admin.VALIDATOR_MESSAGE_ALPHA": "{name} is not only letters.",
    "Admin.VALIDATOR_MESSAGE_DEFAULT": "{name} is not a valid value."
});
}