// This file was generated by silverstripe/tx-translator from client/lang/src/zh.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('zh', {
    "Admin.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "Admin.BATCH_PUBLISH_PROMPT": "您已选了{num}个页面。\n\n是否确定要发布？",
    "Admin.BATCH_UNPUBLISH_PROMPT": "您已选了{num}个页面。\n\n是否确定要取消发布",
    "Admin.CONFIRMUNSAVED": "您确定要离开此页面？\n警告：您所做的更改尚未保存。\n请按“确定”继续，或“取消”留在当前页面。\n",
    "Admin.CONFIRMUNSAVEDSHORT": "警告：您所做的更改尚未保存。",
    "Admin.SELECTONEPAGE": "请至少选择一个页面",
    "Admin.VALIDATIONERROR": "验证错误"
});
}